$schema: "./settings.schema.yaml"
# ---------- Application settings ----- #
environment: development

accounts:
  # generate service token for development (https://api.innohassle.ru/accounts/v0)
  # /tokens/generate-service-token
  api_jwt_token: "some-jwt-token"

rooms:
  - id: "301"
    title: "Lecture Room 301"
    short_name: "301"
    resource_email: ""
    my_uni_id: 1
