$schema: "./settings.schema.yaml"
# ---------- Application settings ----- #
environment: development

accounts:
  # Get from https://api.innohassle.ru/accounts/v0/tokens/generate-service-token?sub=room-booking-local-dev&scopes=users&only_for_me=true
  api_jwt_token: null

exchange:
  username: null
  password: null

my_uni:
  secret_token: null

rooms:
  - id: "301"
    title: "Lecture Room 301"
    short_name: "301"
    resource_email: ""
    my_uni_id: 1
