$schema: "./settings.schema.yaml"
# ---------- Application settings ----- #
accounts:
  api_url: https://api.innohassle.ru/accounts/v0
  well_known_url: https://api.innohassle.ru/accounts/v0/.well-known

rooms:
  - id: "301"
    title: "Lecture Room 301"
    ics_url: ""
    my_uni_id: 1
